POST http://localhost:3000/register
Content-Type : application/json

{
    "username": "revathjsndji",
    "name" :"novathi",
    "password" : "reva",
    "gender" : "male",
    "location" :"hyderabad"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "reva",
    "password" : "reva"
}